### ISSUE TITLE
Export K6 test result and setup monitoring

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#111]
### Background:
Our K6 tests produce JSON outputed results in the format:

```json
{"type":"Point","data":{"time":"2020-12-11T19:41:09.660507348Z","value":206.209713,"tags":{"group":"","method":"POST","name":"https://sso-125-devops-sso-sandbox.pathfinder.gov.bc.ca/auth/realms/ng4ehfvx/protocol/openid-connect/token","proto":"HTTP/1.1","scenario":"default","status":"200","tls_version":"tls1.2","url":"https://sso-125-devops-sso-sandbox.pathfinder.gov.bc.ca/auth/realms/ng4ehfvx/protocol/openid-connect/token"}},"metric":"http_req_duration"}
```
Now that we have K6 test setup already, we need a way to export the test result and be able to send out notification/alert when things fail.

### Tasks:
- [x] create a simple server to test prometheus metric exporting
- [ ] modify server to surface the JSON stats from k6 as prometheus metrics
- [ ] get sysdig to pick up these metrics and display them as a time series chart

**Comment by patricksimonian** [comment]
looks like there is a prometheus exporter called json exporter that we can use.

**Comment by patricksimonian** [comment]
I've created a simple go server that exposes prometheus metrics at the endpoint 'GET /metrics` in klab.

**Comment by patricksimonian** [comment]
meeting setup with Shea to discuss how to export results into sysdig. It looks like its impossible but the initial crack at it didn't work. This meeting is setup for this friday

**Comment by patricksimonian** [comment]
had a great discussion with Shea. The next steps is to deploy our k6 sample exporter app to ARO pathfinder for him to poke around with!

**Comment by patricksimonian** [comment]
K6 deployed to ARO for testing. Shea will update me when he's poked around

**Comment by brycereid73** [comment]
I accidently moved this issue from being blocked.

**Comment by jlangy** [comment]
Hello @patricksimonian @ShellyXueHan , I am working with the SSO team to go through some older issues in here. Is this issue still being worked on/ongoing or did it end up not being possible to get results to sysdig? Thanks for any help :)

**Comment by zsamji** [comment]
Will expand current K6 testing if needed. is "overkill" in our current deployment model
