### ISSUE TITLE
Check on all app realms and deprecate not used themes

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#45]
### background:
we have duplicated themes for sso bcgov login, need to remove the ones not supported anymore.

### Tasks:
- [x] create scripts to check for themes used in dev/test/prod
- [ ] notify sso community to switch to supported themes (sso channel/TIB/email)
- [ ] change management scheduling
- [ ] remove themes not used anymore, and redeploy

**Comment by zsamji** [comment]
working on this currently in keycloak profile
