### ISSUE TITLE
Update SSO deployment with new resource settings

### ISSUE THREAD

**Issue by ShellyXueHan** [bcgov/ocp-sso#88]
### Background:
Have observed out of memory errors on some pods (during service troubleshooting), and identified that the default application deployment does not set a memory request (only a limit).  In order to stabilize the memory resources for the application pods we want to verify application resource requests meet recommended settings.

Additional background from RedHat suggests verifying JVM memory pool sizes are appropriate for the expected workload.

### Tasks:
- [ ] work with RedHat support to identify recommended resource levels for SSO app pods, and any recommended jboss configuration variables.
- [ ] Sandbox: update sso deployment with the identified resource and application settings
- [ ] Sandbox: load test to confirm pod capacity and resource consumption expectations.
- [ ] Dev: update sso deployment with the identified resource and application settings
- [ ] Dev: load test to confirm pod capacity and resource consumption expectations.
- [ ] Test: update sso deployment with the tested resource and application settings
- [ ] Test: load test to confirm pod capacity and resource consumption expectations. (is this step required?)
- [ ] Prod: update sso deployment with the tested resource and application settings

**Comment by ShellyXueHan** [comment]
Update:
This is currently waiting for more information from metrics analyze as well as RedHat review.

**Comment by ShellyXueHan** [comment]
https://github.com/bcgov/ocp-sso/pull/121
